let data = {
  code: 0,
  data: {
    id: 12,
    schoolId: 34,
    assessProjId: 82,
    reportName: '广州信息技术职业学校高水平中职学校建设项目',
    statusCd: 'S01',
    effectDate: '2025-03-28 00:00',
    isPublic: '1',
    bannerUrl: '/2025/01/07/1736224543084.jpg',
    createTime: '2024-12-09 17:07',
    updateTime: '2024-12-09 17:08',
    publicTime: '2025-01-24 17:04',
    password: 'xxjs@321',
    reportColumnList: [
      {
        id: 62,
        reportId: 12,
        columnName: '申报书',
        columnType: 'T01',
        statusCd: 'S01',
        createTime: '2024-12-09',
        updateTime: '2024-12-09',
        children: [
          {
            id: 285,
            reportId: 12,
            columnName: '申报书',
            columnType: 'T01',
            attachUrl: '/2024/12/27/1735309413197.pdf',
            statusCd: 'S01',
            createTime: '2024-12-27',
            parentId: 62,
            attachName: '1.《申报书》.pdf',
            isShowYear: '0',
            parentName: '申报书',
            isShowTaskRemark: '1',
          },
        ],
        rank: 0,
        isShowTaskRemark: '1',
      },
      {
        id: 126,
        reportId: 12,
        columnName: '建设方案',
        columnType: 'T01',
        statusCd: 'S01',
        createTime: '2024-12-14',
        updateTime: '2024-12-14',
        children: [
          {
            id: 286,
            reportId: 12,
            columnName: '建设方案',
            columnType: 'T01',
            attachUrl: '/2024/12/27/1735309464491.pdf',
            statusCd: 'S01',
            createTime: '2024-12-27',
            parentId: 126,
            attachName: '2.《建设方案》.pdf',
            isShowYear: '0',
            parentName: '建设方案',
            isShowTaskRemark: '1',
          },
        ],
        rank: 1,
        isShowTaskRemark: '1',
      },
      {
        id: 63,
        reportId: 12,
        columnName: '任务书',
        columnType: 'T01',
        statusCd: 'S01',
        createTime: '2024-12-09',
        updateTime: '2024-12-09',
        children: [
          {
            id: 287,
            reportId: 12,
            columnName: '任务书',
            columnType: 'T01',
            attachUrl: '/2024/12/27/1735309495116.pdf',
            statusCd: 'S01',
            createTime: '2024-12-27',
            parentId: 63,
            attachName: '3.《任务书》.pdf',
            isShowYear: '0',
            parentName: '任务书',
            isShowTaskRemark: '1',
          },
        ],
        rank: 2,
        isShowTaskRemark: '1',
      },
      {
        id: 64,
        reportId: 12,
        columnName: '期满验收自评报告',
        columnType: 'T01',
        statusCd: 'S01',
        createTime: '2024-12-09',
        updateTime: '2024-12-09',
        children: [
          {
            id: 70,
            reportId: 12,
            columnName: '学校层面',
            columnType: 'T01',
            attachUrl: '/2025/01/24/1737707763600.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-24',
            projId: 94731,
            parentId: 64,
            attachName: '附件2. 期满验收自评报告（学校层面盖章终稿）1-24.pdf',
            isShowYear: '0',
            parentName: '期满验收自评报告',
            reportColumnAttachList: [
              {
                id: 162,
                attachName: '附件2. 期满验收自评报告（学校层面盖章终稿）1-24.docx',
                attachUrl: '/2025/01/24/1737707790220.docx',
                reportColumnId: 70,
                createTime: '2025-01-24 16:36',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 71,
            reportId: 12,
            columnName: '专业群1',
            columnType: 'T01',
            attachUrl: '/2025/01/24/1737709317888.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-24',
            projId: 94738,
            parentId: 64,
            attachName: '附件2. 期满验收自评报告（专业群一）（盖章版)1-24.pdf',
            isShowYear: '0',
            parentName: '期满验收自评报告',
            reportColumnAttachList: [
              {
                id: 164,
                attachName: '附件2. 期满验收自评报告（专业群一）（盖章版)1-24 .docx',
                attachUrl: '/2025/01/24/1737709324463.docx',
                reportColumnId: 71,
                createTime: '2025-01-24 17:02',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 72,
            reportId: 12,
            columnName: '专业群2',
            columnType: 'T01',
            attachUrl: '/2025/01/24/1737707808364.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-24',
            projId: 94737,
            parentId: 64,
            attachName: '附件2. 期满验收自评报告（专业群二）（盖章版)1-24.pdf',
            isShowYear: '0',
            parentName: '期满验收自评报告',
            reportColumnAttachList: [
              {
                id: 163,
                attachName: '附件2. 期满验收自评报告（专业群二）（盖章版)1-24.docx',
                attachUrl: '/2025/01/24/1737707816726.docx',
                reportColumnId: 72,
                createTime: '2025-01-24 16:37',
              },
            ],
            isShowTaskRemark: '1',
          },
        ],
        rank: 3,
        isShowTaskRemark: '1',
      },
      {
        id: 65,
        reportId: 12,
        columnName: '期满任务完成情况自评表',
        columnType: 'T01',
        statusCd: 'S01',
        createTime: '2024-12-09',
        updateTime: '2024-12-09',
        children: [
          {
            id: 73,
            reportId: 12,
            columnName: '学校层面',
            columnType: 'T01',
            attachUrl: '/2025/01/18/1737164023632.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-18',
            parentId: 65,
            attachName: '附件3.学校层面期满任务完成情况自评表（学校层面）（盖章版）.pdf',
            isShowYear: '0',
            parentName: '期满任务完成情况自评表',
            reportColumnAttachList: [
              {
                id: 156,
                attachName: '附件3.学校层面期满任务完成情况自评表（学校层面）.doc',
                attachUrl: '/2025/01/18/1737164027019.doc',
                reportColumnId: 73,
                createTime: '2025-01-18 09:33',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 74,
            reportId: 12,
            columnName: '专业群1',
            columnType: 'T01',
            attachUrl: '/2025/01/06/1736130212329.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-06',
            parentId: 65,
            attachName: '4.《期满任务完成情况自评表》专业群一.pdf',
            isShowYear: '0',
            parentName: '期满任务完成情况自评表',
            reportColumnAttachList: [
              {
                id: 91,
                attachName: '4.《期满任务完成情况自评表》专业群一.doc',
                attachUrl: '/2025/01/06/1736130215255.doc',
                reportColumnId: 74,
                createTime: '2025-01-06 10:23',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 75,
            reportId: 12,
            columnName: '专业群2',
            columnType: 'T01',
            attachUrl: '/2025/01/18/1737164064393.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-18',
            parentId: 65,
            attachName: '附件3.学校层面期满任务完成情况自评表（专业群二）（盖章版）.pdf',
            isShowYear: '0',
            parentName: '期满任务完成情况自评表',
            reportColumnAttachList: [
              {
                id: 157,
                attachName: '附件3.学校层面期满任务完成情况自评表（专业群二）.doc',
                attachUrl: '/2025/01/18/1737164068795.doc',
                reportColumnId: 75,
                createTime: '2025-01-18 09:34',
              },
            ],
            isShowTaskRemark: '1',
          },
        ],
        rank: 4,
        isShowTaskRemark: '1',
      },
      {
        id: 66,
        reportId: 12,
        columnName: '期满绩效自评表',
        columnType: 'T01',
        statusCd: 'S01',
        createTime: '2024-12-09',
        updateTime: '2024-12-09',
        children: [
          {
            id: 76,
            reportId: 12,
            columnName: '学校层面',
            columnType: 'T01',
            attachUrl: '/2025/01/18/1737164086645.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-18',
            parentId: 66,
            attachName: '附件4.期满绩效自评表（学校层面）（盖章版）.pdf',
            isShowYear: '0',
            parentName: '期满绩效自评表',
            reportColumnAttachList: [
              {
                id: 158,
                attachName: '附件4.期满绩效自评表（学校层面）.docx',
                attachUrl: '/2025/01/18/1737164090051.docx',
                reportColumnId: 76,
                createTime: '2025-01-18 09:34',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 77,
            reportId: 12,
            columnName: '专业群1',
            columnType: 'T01',
            attachUrl: '/2025/01/06/1736130241421.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-06',
            parentId: 66,
            attachName: '5.《期满绩效自评表》专业群一.pdf',
            isShowYear: '0',
            parentName: '期满绩效自评表',
            reportColumnAttachList: [
              {
                id: 93,
                attachName: '5.《期满绩效自评表》专业群一.docx',
                attachUrl: '/2025/01/06/1736130245183.docx',
                reportColumnId: 77,
                createTime: '2025-01-06 10:24',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 78,
            reportId: 12,
            columnName: '专业群2',
            columnType: 'T01',
            attachUrl: '/2025/01/06/1736130255763.pdf',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-06',
            parentId: 66,
            attachName: '5.《期满绩效自评表》专业群二.pdf',
            isShowYear: '0',
            parentName: '期满绩效自评表',
            reportColumnAttachList: [
              {
                id: 94,
                attachName: '5.《期满绩效自评表》专业群二.docx',
                attachUrl: '/2025/01/06/1736130258989.docx',
                reportColumnId: 78,
                createTime: '2025-01-06 10:24',
              },
            ],
            isShowTaskRemark: '1',
          },
        ],
        rank: 5,
        isShowTaskRemark: '1',
      },
      {
        id: 67,
        reportId: 12,
        columnName: '标志性成果一览表',
        columnType: 'T01',
        statusCd: 'S01',
        createTime: '2024-12-09',
        updateTime: '2024-12-09',
        children: [
          {
            id: 139,
            reportId: 12,
            columnName: '学校层面',
            columnType: 'T01',
            attachUrl: '/2025/01/06/1736129270143.pdf',
            statusCd: 'S01',
            createTime: '2024-12-14',
            updateTime: '2025-01-06',
            parentId: 67,
            attachName: '6.《标志性成果一览表》.pdf',
            isShowYear: '0',
            parentName: '标志性成果一览表',
            reportColumnAttachList: [
              {
                id: 84,
                attachName: '6.《标志性成果一览表》.docx',
                attachUrl: '/2025/01/06/1736129275946.docx',
                reportColumnId: 139,
                createTime: '2025-01-06 10:07',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 140,
            reportId: 12,
            columnName: '专业群1',
            columnType: 'T01',
            attachUrl: '/2025/01/06/1736130288176.pdf',
            statusCd: 'S01',
            createTime: '2024-12-14',
            updateTime: '2025-01-06',
            parentId: 67,
            attachName: '6.《标志性成果一览表》专业群一(1).pdf',
            isShowYear: '0',
            parentName: '标志性成果一览表',
            reportColumnAttachList: [
              {
                id: 96,
                attachName: '6.《标志性成果一览表》专业群一.docx',
                attachUrl: '/2025/01/06/1736130284477.docx',
                reportColumnId: 140,
                createTime: '2025-01-06 10:24',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 141,
            reportId: 12,
            columnName: '专业群2',
            columnType: 'T01',
            attachUrl: '/2025/01/06/1736130268874.pdf',
            statusCd: 'S01',
            createTime: '2024-12-14',
            updateTime: '2025-01-06',
            parentId: 67,
            attachName: '6.《标志性成果一览表》专业群二.pdf',
            isShowYear: '0',
            parentName: '标志性成果一览表',
            reportColumnAttachList: [
              {
                id: 95,
                attachName: '6.《标志性成果一览表》专业群二.docx',
                attachUrl: '/2025/01/06/1736130270952.docx',
                reportColumnId: 141,
                createTime: '2025-01-06 10:24',
              },
            ],
            isShowTaskRemark: '1',
          },
        ],
        rank: 6,
        isShowTaskRemark: '1',
      },
      {
        id: 68,
        reportId: 12,
        columnName: '典型案例',
        columnType: 'T01',
        statusCd: 'S01',
        createTime: '2024-12-09',
        updateTime: '2024-12-09',
        children: [
          {
            id: 353,
            reportId: 12,
            columnName: '典型案例1',
            columnType: 'T01',
            attachUrl: '/2025/01/24/1737707581516.pdf',
            statusCd: 'S01',
            createTime: '2025-01-05',
            updateTime: '2025-01-24',
            parentId: 68,
            attachName: '7.《典型案例》1：““一引领、二核心、三体系、四阶段”打造良将金师 赋能学校高质量发展.pdf',
            isShowYear: '0',
            parentName: '典型案例',
            reportColumnAttachList: [
              {
                id: 159,
                attachName: '7.《典型案例》1：““一引领、二核心、三体系、四阶段”打造良将金师 赋能学校高质量发展 .docx',
                attachUrl: '/2025/01/24/1737707589841.docx',
                reportColumnId: 353,
                createTime: '2025-01-24 16:33',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 355,
            reportId: 12,
            columnName: '典型案例2',
            columnType: 'T01',
            attachUrl: '/2025/01/24/1737707624997.pdf',
            statusCd: 'S01',
            createTime: '2025-01-05',
            updateTime: '2025-01-24',
            parentId: 68,
            attachName: '7.《典型案例》2：政校行企多元协同：育训结合、双平台四进阶的中职人工智能专业人才培养模式构建.pdf',
            isShowYear: '0',
            parentName: '典型案例',
            reportColumnAttachList: [
              {
                id: 160,
                attachName: '7.《典型案例》2：政校行企多元协同：育训结合、双平台四进阶的中职人工智能专业人才培养模式构建.docx',
                attachUrl: '/2025/01/24/1737707631730.docx',
                reportColumnId: 355,
                createTime: '2025-01-24 16:33',
              },
            ],
            isShowTaskRemark: '1',
          },
          {
            id: 356,
            reportId: 12,
            columnName: '典型案例3',
            columnType: 'T01',
            attachUrl: '/2025/01/24/1737707642209.pdf',
            statusCd: 'S01',
            createTime: '2025-01-05',
            updateTime: '2025-01-24',
            parentId: 68,
            attachName: '7.《典型案例》3：产教融合“二三四五”中职信息技术人才培养模式.pdf',
            isShowYear: '0',
            parentName: '典型案例',
            reportColumnAttachList: [
              {
                id: 161,
                attachName: '7.《典型案例》3：产教融合“二三四五”中职信息技术人才培养模式.docx',
                attachUrl: '/2025/01/24/1737707647975.docx',
                reportColumnId: 356,
                createTime: '2025-01-24 16:34',
              },
            ],
            isShowTaskRemark: '1',
          },
        ],
        rank: 7,
        isShowTaskRemark: '1',
      },
      {
        id: 69,
        reportId: 12,
        columnName: '佐证材料',
        columnType: 'T07',
        statusCd: 'S01',
        createTime: '2024-12-09',
        updateTime: '2024-12-09',
        children: [
          {
            id: 85,
            reportId: 12,
            columnName: '学校层面',
            columnType: 'T02',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2024-12-09',
            projId: 94731,
            parentId: 69,
            children: [
              {
                id: 88,
                reportId: 12,
                columnName: '1.建设任务',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2024-12-09',
                projId: 94732,
                parentId: 85,
                children: [
                  {
                    id: 293,
                    reportId: 12,
                    columnName: '1.加强党的建设',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92454,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 294,
                    reportId: 12,
                    columnName: '2.落实立德树人',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92455,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 295,
                    reportId: 12,
                    columnName: '3.打造高水平专业群',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92456,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 296,
                    reportId: 12,
                    columnName: '4.打造高水平双师队伍',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92457,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 297,
                    reportId: 12,
                    columnName: '5.提升校企合作水平',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92458,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 298,
                    reportId: 12,
                    columnName: '6.提升学校治理能力',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92459,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 299,
                    reportId: 12,
                    columnName: '7.提升社会服务水平',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92460,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 300,
                    reportId: 12,
                    columnName: '8.提升信息化水平',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92461,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 301,
                    reportId: 12,
                    columnName: '9.提升国际及粤港澳台交流水平',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92462,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 303,
                    reportId: 12,
                    columnName: '10.特色发展',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92463,
                    parentId: 88,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '学校层面',
                isShowTaskRemark: '1',
              },
              {
                id: 89,
                reportId: 12,
                columnName: '2.绩效目标',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2024-12-09',
                projId: 94733,
                parentId: 85,
                children: [
                  {
                    id: 310,
                    reportId: 12,
                    columnName: '产出指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94896,
                    parentId: 89,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 313,
                    reportId: 12,
                    columnName: '时效指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94797,
                    parentId: 89,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 319,
                    reportId: 12,
                    columnName: '满意度指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94798,
                    parentId: 89,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '学校层面',
                isShowTaskRemark: '1',
              },
              {
                id: 90,
                reportId: 12,
                columnName: '3.社会效益',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2025-01-06',
                projId: 94734,
                parentId: 85,
                isShowYear: '0',
                parentName: '学校层面',
                isShowTaskRemark: '0',
              },
              {
                id: 91,
                reportId: 12,
                columnName: '4.项目建设资金与项目管理',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2025-01-06',
                projId: 94771,
                parentId: 85,
                children: [
                  {
                    id: 367,
                    reportId: 12,
                    columnName: '4.1项目建设资金预算、到位与支出情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/18/1737164872207.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-18',
                    parentId: 91,
                    attachName: '4.1 项目建设资金预算、到位与支出情况佐证材料(1).pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 368,
                    reportId: 12,
                    columnName: '4.2项目管理情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/18/1737164167288.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-18',
                    parentId: 91,
                    attachName: '4.2 项目管理佐证材料.pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 369,
                    reportId: 12,
                    columnName: '4.3资金管理情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/06/1736136360191.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-06',
                    parentId: 91,
                    attachName: '4.3 资金管理佐证材料.pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '学校层面',
                isShowTaskRemark: '0',
              },
              {
                id: 92,
                reportId: 12,
                columnName: '5.标志性成果',
                columnType: 'T04',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2025-01-06',
                projId: 96593,
                parentId: 85,
                templateTableId: 6,
                isShowYear: '0',
                parentName: '学校层面',
                isShowTaskRemark: '1',
              },
            ],
            isShowYear: '0',
            parentName: '佐证材料',
            isShowTaskRemark: '1',
          },
          {
            id: 86,
            reportId: 12,
            columnName: '专业群1（电子技术应用专业群）',
            columnType: 'T02',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-06',
            projId: 94738,
            parentId: 69,
            children: [
              {
                id: 93,
                reportId: 12,
                columnName: '1.建设任务',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2024-12-09',
                projId: 94767,
                parentId: 86,
                children: [
                  {
                    id: 302,
                    reportId: 12,
                    columnName: '1.人才培养模式创新',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92464,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 304,
                    reportId: 12,
                    columnName: '2.课程教学资源建设',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2025-01-03',
                    projId: 92465,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 305,
                    reportId: 12,
                    columnName: '3.教材与教法改革',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92466,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 306,
                    reportId: 12,
                    columnName: '4.教师教学创新团队',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92467,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 307,
                    reportId: 12,
                    columnName: '5.实践教学基地',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92468,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 308,
                    reportId: 12,
                    columnName: '6.社会服务',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92469,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 311,
                    reportId: 12,
                    columnName: '7.国际及粤港澳台交流与合作',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2025-01-03',
                    projId: 92470,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 312,
                    reportId: 12,
                    columnName: '8.可持续发展保障机制',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2025-01-03',
                    projId: 92471,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 342,
                    reportId: 12,
                    columnName: '9.特色项目',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2025-01-03',
                    projId: 95184,
                    parentId: 93,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '专业群1（电子技术应用专业群）',
                isShowTaskRemark: '1',
              },
              {
                id: 94,
                reportId: 12,
                columnName: '2.绩效目标',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2024-12-09',
                projId: 94768,
                parentId: 86,
                children: [
                  {
                    id: 314,
                    reportId: 12,
                    columnName: '产出指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94890,
                    parentId: 94,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 315,
                    reportId: 12,
                    columnName: '时效指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94791,
                    parentId: 94,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 316,
                    reportId: 12,
                    columnName: '满意度指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94792,
                    parentId: 94,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '专业群1（电子技术应用专业群）',
                isShowTaskRemark: '1',
              },
              {
                id: 95,
                reportId: 12,
                columnName: '3.社会效益',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2025-01-06',
                projId: 94769,
                parentId: 86,
                isShowYear: '0',
                parentName: '专业群1（电子技术应用专业群）',
                isShowTaskRemark: '0',
              },
              {
                id: 370,
                reportId: 12,
                columnName: '4.项目建设资金与项目管理',
                columnType: 'T01',
                statusCd: 'S01',
                createTime: '2025-01-06',
                parentId: 86,
                children: [
                  {
                    id: 372,
                    reportId: 12,
                    columnName: '4.1目建设资金预算、到位与支出情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/20/1737377683303.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-20',
                    parentId: 370,
                    attachName: '4.1 专业群1.项目建设资金预算、到位与支出情况佐证材料（加超链接）.pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 373,
                    reportId: 12,
                    columnName: '4.2项目管理情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/17/1737076827234.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-17',
                    parentId: 370,
                    attachName: '4.2 专业群一 项目管理佐证材料.pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 374,
                    reportId: 12,
                    columnName: '4.3资金管理情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/17/1737110220585.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-17',
                    parentId: 370,
                    attachName: '4.3 专业群一 资金管理佐证材料.pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '专业群1（电子技术应用专业群）',
                isShowTaskRemark: '1',
              },
              {
                id: 371,
                reportId: 12,
                columnName: '5.标志性成果',
                columnType: 'T04',
                statusCd: 'S01',
                createTime: '2025-01-06',
                updateTime: '2025-01-06',
                projId: 94895,
                parentId: 86,
                templateTableId: 6,
                isShowYear: '0',
                parentName: '专业群1（电子技术应用专业群）',
                isShowTaskRemark: '1',
              },
            ],
            isShowYear: '0',
            parentName: '佐证材料',
            isShowTaskRemark: '1',
          },
          {
            id: 87,
            reportId: 12,
            columnName: '专业群2（现代通信技术应用专业群）',
            columnType: 'T02',
            statusCd: 'S01',
            createTime: '2024-12-09',
            updateTime: '2025-01-06',
            projId: 94737,
            parentId: 69,
            children: [
              {
                id: 97,
                reportId: 12,
                columnName: '1.建设任务',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2024-12-09',
                projId: 94764,
                parentId: 87,
                children: [
                  {
                    id: 317,
                    reportId: 12,
                    columnName: '1.人才培养模式创新',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92472,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 318,
                    reportId: 12,
                    columnName: '2.课程教学资源建设',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92473,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 320,
                    reportId: 12,
                    columnName: '3.教材与教法改革',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92474,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 321,
                    reportId: 12,
                    columnName: '4.教师教学创新团队',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92475,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 322,
                    reportId: 12,
                    columnName: '5.实践教学基地',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92476,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 323,
                    reportId: 12,
                    columnName: '6.技术平台',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92477,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 324,
                    reportId: 12,
                    columnName: '7.社会服务',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92478,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 325,
                    reportId: 12,
                    columnName: '8.国际及粤港澳台交流与合作',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92479,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 326,
                    reportId: 12,
                    columnName: '9.可持续发展保障机制',
                    columnType: 'T02',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    projId: 92480,
                    parentId: 97,
                    isShowYear: '0',
                    parentName: '1.建设任务',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '专业群2（现代通信技术应用专业群）',
                isShowTaskRemark: '1',
              },
              {
                id: 98,
                reportId: 12,
                columnName: '2.绩效目标',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2024-12-09',
                projId: 94765,
                parentId: 87,
                children: [
                  {
                    id: 327,
                    reportId: 12,
                    columnName: '产出指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94793,
                    parentId: 98,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 328,
                    reportId: 12,
                    columnName: '时效指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94794,
                    parentId: 98,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 329,
                    reportId: 12,
                    columnName: '满意度指标',
                    columnType: 'T06',
                    statusCd: 'S01',
                    createTime: '2024-12-31',
                    updateTime: '2024-12-31',
                    projId: 94795,
                    parentId: 98,
                    isShowYear: '0',
                    parentName: '2.绩效目标',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '专业群2（现代通信技术应用专业群）',
                isShowTaskRemark: '1',
              },
              {
                id: 99,
                reportId: 12,
                columnName: '3.社会效益',
                columnType: 'T02',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2025-01-06',
                projId: 94766,
                parentId: 87,
                isShowYear: '0',
                parentName: '专业群2（现代通信技术应用专业群）',
                isShowTaskRemark: '0',
              },
              {
                id: 100,
                reportId: 12,
                columnName: '4.项目建设资金与项目管理',
                columnType: 'T01',
                statusCd: 'S01',
                createTime: '2024-12-09',
                updateTime: '2025-01-06',
                parentId: 87,
                children: [
                  {
                    id: 375,
                    reportId: 12,
                    columnName: '4.1项目建设资金预算、到位与支出情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/17/1737110174454.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-17',
                    parentId: 100,
                    attachName: '4.1专业群2.项目建设资金预算、到位与支出情况(1).pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 376,
                    reportId: 12,
                    columnName: '4.2项目管理情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/17/1737110086394.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-17',
                    parentId: 100,
                    attachName: '4.2项目管理佐证材料1(1).pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                  {
                    id: 377,
                    reportId: 12,
                    columnName: '4.3资金管理情况',
                    columnType: 'T01',
                    attachUrl: '/2025/01/17/1737076985189.pdf',
                    statusCd: 'S01',
                    createTime: '2025-01-06',
                    updateTime: '2025-01-17',
                    parentId: 100,
                    attachName: '4.3 资金管理.pdf',
                    isShowYear: '0',
                    parentName: '4.项目建设资金与项目管理',
                    isShowTaskRemark: '1',
                  },
                ],
                isShowYear: '0',
                parentName: '专业群2（现代通信技术应用专业群）',
                isShowTaskRemark: '1',
              },
              {
                id: 378,
                reportId: 12,
                columnName: '5.标志性成果',
                columnType: 'T04',
                statusCd: 'S01',
                createTime: '2025-01-06',
                updateTime: '2025-01-06',
                projId: 95090,
                parentId: 87,
                templateTableId: 6,
                isShowYear: '0',
                parentName: '专业群2（现代通信技术应用专业群）',
                isShowTaskRemark: '1',
              },
            ],
            isShowYear: '0',
            parentName: '佐证材料',
            isShowTaskRemark: '1',
          },
        ],
        rank: 8,
        isShowTaskRemark: '1',
      },
    ],
  },
  msg: '执行成功',
};
